version: 0.2

phases: 
    install:
        commands:
            - echo "Enter the install phase on 'date'"
            - apt-get update -y
            - apt-get install -y maven  
    build:
        commands:
            - echo "Enter the Buld phase on 'date'"
            - mvn install  
    post_build:
        commands:
            - echo Build completed on 'date'
artifacts:
    files:
      - '**/*'
            
